### ISSUE TITLE
Module fails to work after install - controller mgr failure

### ISSUE THREAD

**Issue by tcskill** [cloud-native-toolkit/terraform-gitops-cp-db2-oltp#10]
Module is not usable after install.  Module fails to start controller manager pods with errors:

I tried re-installing this looks like an issue with the oltp operator.  the operator-controller-manager won't start properly and has this error:

W0411 20:03:14.768689       7 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list /v1, Kind=ConfigMap: configmaps is forbidden: User "system:serviceaccount:cpd-operators:ibm-db2oltp-cp4d-operator-db2u-cp4d-operator" cannot list resource "configmaps"

@triceam fyi

**Comment by seansund** [comment]
Required steps here - https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=tasks-creating-operator-subscriptions

**Comment by balasgit** [comment]
PR is released - https://github.com/cloud-native-toolkit/terraform-gitops-cp-db2-oltp/pull/12

**Comment by balasgit** [comment]
The issue has been fixed as part of PR
