### ISSUE TITLE
DB2 OLTP - Missed to implement operator

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/terraform-gitops-cp-db2-oltp#11]
Working with CP4D Squad who have knowledge on DB2.

Updates from @spansare 12th April

https://ibm-cloudplatform.slack.com/archives/C02KB99P2JC/p1649742543445999?thread_ts=1649724790.600559&cid=C02KB99P2JC 

**Action**  - snehal will fix tomorrow morning.
 Its an edit that needs to be run on operandRegistry. Will have to check on how to run it.

**Comment by tcskill** [comment]
@balasgit is this different than issue #10 ?

**Comment by balasgit** [comment]
@tcskill - created based on the slack updates.. Let me validate with snehal if this is same and we can close this one if requried.

**Comment by balasgit** [comment]
Issue is addressed and PR code is released..

**Comment by balasgit** [comment]
PR - https://github.com/cloud-native-toolkit/terraform-gitops-cp-db2-oltp/pull/12
